---
- name: Allow to run `sudo pacman` without a password for {{ ansible_user }}
  community.general.sudoers:
    name: "run-pacman-no-password"
    user: "{{ ansible_user }}"
    commands: /usr/bin/pacman
    nopassword: true
  become: true

- name: Delete .bash_profile of {{ ansible_user }}
  ansible.builtin.file:
    path: ~/.bash_profile
    state: absent
