---
repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint
        args: ["--strict"]
        language: system
        files: \.(yml|yaml)$
      - id: check-yaml
        name: yamllint
        entry: yamllint
        args: ["--strict"]
        language: system
        files: \.(yml|yaml)$
