---
- name: Setup Dev environment for Arch Linux
  hosts: all
  pre_tasks:
    - name: Update pacman packages
      ansible.builtin.include_tasks:
        file: roles/pacman/tasks/update.yml
  roles:
    - role: setup-user
      tags: setup-user

    - role: pacman
      tags: pacman

    - role: aur-packages
      tags: aur

    - role: flatpak
      tags: flatpak

    - role: config
      tags: config

  tasks:
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Reboot the machine
      become: true
      ansible.builtin.reboot:
        reboot_timeout: 3000
      notify: "reboot done"
