---
- name: Setup Dev environment for Arch Linux
  hosts: all
  pre_tasks:
    - name: Update pacman packages
      include_tasks:
        file: roles/pacman/tasks/update.yml
  roles:
    - role: setup-user
    - role: pacman
    - role: aur-packages
    - role: config

  tasks:
    - name: Flush handlers
      meta: flush_handlers

    - name: Reboot the machine
      become: true
      reboot:
        reboot_timeout: 3000
      notify: "reboot done"
