---
- name: Update Arch Linux
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update pacman packages
      ansible.builtin.include_tasks:
        file: roles/pacman/tasks/update.yml

    - name: Update AUR packages
      ansible.builtin.include_tasks:
        file: roles/aur-packages/tasks/update.yml

    - name: Update flatpak packages
      ansible.builtin.include_tasks:
        file: roles/flatpak/tasks/update.yml

    - name: Include config vars
      ansible.builtin.include_vars: roles/config/defaults/main.yml

    - name: Update configured packages
      ansible.builtin.include_tasks:
        file: roles/config/tasks/update.yml

    - name: Update rust
      ansible.builtin.command: rustup update
      register: rustup_result
      changed_when: "'updated' in rustup_result.stdout"

  handlers:
    - name: Updated pacman packages
      ansible.builtin.debug:
        var: updated_pacman_packages.packages
      when: (updated_pacman_packages.packages | default(false))
      listen: "pacman_update"

    - name: Updated flatpak packages
      ansible.builtin.debug:
        var: updated_flatpak_packages.stdout_lines
      when: updated_flatpak_packages.changed
      listen: "flatpak_update"
