---
- name: Update Arch Linux
  hosts: all
  tasks:
    - name: Update pacman packages
      include_tasks:
        file: roles/pacman/tasks/update.yml

    - name: Update AUR packages
      include_tasks:
        file: roles/aur-packages/tasks/update.yml

    - name: Include config vars
      include_vars: roles/config/defaults/main.yml

    - name: Update configured packages
      include_tasks:
        file: roles/config/tasks/update.yml
