---
pacman_packages:
  - git
  - base-devel
  - arandr
  - lightdm
  - lightdm-gtk-greeter
  - qtile
  - network-manager-applet
  - blueman
  - pcmanfm
  - picom
  - nitrogen
  - rofi
  - firefox
  - xterm
  - kitty
  - zsh
  - stow
  - starship
  - bat
  - fd
  - neovim
  - fzf
  - ripgrep
  - git-delta
  - httpie
  - python-pipx
  - hub
  - tree
  - jq
  - shfmt
  - xclip
  - tmux
  - direnv
  - difftastic
  - btop
  - ctags
  - postgresql
  - curl
  - wget
  - brightnessctl
  - noto-fonts
  - stylua
  - shellcheck
