---
pacman_packages:
  ############################
  ######## DEV TOOLS #########
  ############################
  - atuin
  - bat
  - btop
  - ctags
  - curl
  - dash
  - docker
  - docker-compose
  - fd
  - fzf
  - git
  - gitui
  - jq
  - luarocks
  - man-db
  - neovim
  - python-pipx
  - ripgrep
  - rustup
  - shfmt
  - starship
  - stow
  - stylua
  - tmux
  - tree
  - unzip
  - viu
  - wget
  - zip
  - zoxide
  - zsh
  #############################
  ######## DESKTOP ENV ########
  #############################
  # Window Manager
  - hyprland
  - wayland
  - waybar
  - polkit-kde-agent
  - xdg-desktop-portal-hyprland
  - qt5-wayland
  - qt6-wayland
  - wl-clipboard
  # Hardware Controllers
  - pipewire
  - pipewire-pulse
  - wireplumber  # pipewire session manager
  - pavucontrol
  - playerctl
  - bluez-utils
  - brightnessctl
  # Applets
  - network-manager-applet
  - blueman
  # Helpers
  - dunst
  - copyq
  # Desktop Applications
  - firefox
  - pcmanfm
  # Screenshot
  - grim
  - slurp
  # Lock screen
  - swaylock
  - swayidle
  # Power management
  - acpica
  ############################
  ######## ARCH TOOLS ########
  ############################
  - base-devel
  - dnsmasq
  - flatpak
  - gnupg
  - neofetch
  - reflector
  ################################
  ### FONTS & TEHEMES & EMOJIS ###
  ################################
  - arc-gtk-theme
  - noto-fonts-emoji
  - papirus-icon-theme
  - ttf-cascadia-code-nerd
  - ttf-iosevkaterm-nerd
  - ttf-jetbrains-mono-nerd
  - ttf-noto-nerd
  ############################
  ### TERMINAL EMULATORS #####
  ############################
  - alacritty
  - kitty
  - wezterm
  ############################
  ######## VM SETUP ##########
  ############################
  - edk2-ovmf
  - libvirt
  - qemu-desktop
  - virt-manager
  ############################
  ######## PRINTER ###########
  ############################
  - cups
  - cups-pdf
  - gutenprint
  - system-config-printer
