---
- name: Run the equivalent of "pacman -Syu"
  become: true
  pacman:
    update_cache: true
    upgrade: true

- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
  become: true
  become_user: "{{ ansible_user }}"
  loop: "{{ aur_packages }}"
  notify: "AUR packages installed"
