---
- name: Create the `aur_builder` user
  user:
    name: aur_builder
    create_home: true
    group: wheel
  become: true

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'
  become: true

- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
  become: true
  become_user: aur_builder
  loop: "{{ aur_packages }}"
