---
- name: Install paru AUR helper
  kewlfft.aur.aur:
    name: paru
    state: present
  become: true
  become_user: "{{ ansible_user }}"
  register: install_paru
  until: "install_paru is not failed"
  delay: 5
  retries: 3

- name: Update cache
  kewlfft.aur.aur:
    upgrade: true
    update_cache: true
  become: true
  become_user: "{{ ansible_user }}"

- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
  become: true
  become_user: "{{ ansible_user }}"
  loop: "{{ aur_packages }}"
  register: install_aur_packages
  until: "install_aur_packages is not failed"
  delay: 5
  retries: 3
