---
- name: Install paru AUR helper
  kewlfft.aur.aur:
    name: paru
    state: present
  become: true
  become_user: "{{ ansible_user }}"

- name: Update cache
  kewlfft.aur.aur:
    upgrade: true
    update_cache: true
  become: true
  become_user: "{{ ansible_user }}"

- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
  become: true
  become_user: "{{ ansible_user }}"
  loop: "{{ aur_packages }}"
  notify: "AUR packages installed"
