---
- name: Enable docker service
  become: true
  ansible.builtin.service:
    name: "docker.service"
    enabled: true
  listen: "pacman packages installed"

- name: Enable cups service
  become: true
  ansible.builtin.service:
    name: "cups.service"
    enabled: true
  listen: "pacman packages installed"

- name: Updated pacman packages
  ansible.builtin.debug:
    var: updated_pacman_packages.packages
  when: updated_pacman_packages.changed
