---
- name: Enable docker service
  become: true
  service:
    name: "docker.service"
    enabled: true
  listen: "pacman packages installed"

- name: Enable cups service
  become: true
  service:
    name: "cups.service"
    enabled: true
  listen: "pacman packages installed"
