---
- name: Enable pacman parallel downloading
  become: true
  lineinfile:
    path: /etc/pacman.conf
    regexp: "ParallelDownloads ="
    line: "ParallelDownloads = 10"

- name: Run the equivalent of "pacman -Syu"
  become: true
  pacman:
    update_cache: true
    upgrade: true

- name: Install packages
  become: true
  pacman:
    name: "{{ pacman_packages }}"
    state: present

- name: Add "{{ ansible_user }}" to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable docker service
  become: true
  service:
    name: "docker.service"
    enabled: true
