---
- name: Enable pacman parallel downloading
  become: true
  lineinfile:
    path: /etc/pacman.conf
    regexp: "ParallelDownloads ="
    line: "ParallelDownloads = 10"

- name: Run the equivalent of "pacman -Syu"
  become: true
  pacman:
    update_cache: true
    upgrade: true

- name: Install pacman packages
  become: true
  pacman:
    name: "{{ pacman_packages }}"
    state: present
  notify: "pacman packages installed"

- name: Find packages to clean
  become: true
  command: pacman -Qqdt
  register: packages_to_clean
  ignore_errors: true

- name: Clean packages
  become: true
  pacman:
    name: "{{ packages_to_clean.stdout_lines }}"
    state: absent
    extra_args: --recursive
  when: packages_to_clean.stdout_lines != []
