---
- name: Enable pacman parallel downloading
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "ParallelDownloads ="
    line: "ParallelDownloads = 10"

- name: Install pacman packages
  become: true
  pacman:
    name: "{{ pacman_packages }}"
    state: present
  notify: "pacman packages installed"
  register: install_pacman_packages_result
  until: "install_pacman_packages_result is not failed"
  delay: 5
  retries: 3

- name: Create pacman hooks folder
  become: true
  ansible.builtin.file:
    path: /etc/pacman.d/hooks/
    mode: "u=rwx,g=rx,o=rx"
    state: directory

- name: Create auto link dash to /bin/sh hook
  become: true
  ansible.builtin.template:
    src: relink-dash.hook.j2
    mode: "u=rw,g=r,o=r"
    dest: "/etc/pacman.d/hooks/relink-dash.hook"
