---
- name: Enable pacman parallel downloading
  become: true
  lineinfile:
    path: /etc/pacman.conf
    regexp: "ParallelDownloads ="
    line: "ParallelDownloads = 10"

- name: Install pacman packages
  become: true
  pacman:
    name: "{{ pacman_packages }}"
    state: present
  notify: "pacman packages installed"
