---
- name: Enable pacman parallel downloading
  become: true
  lineinfile:
    path: /etc/pacman.conf
    regexp: "ParallelDownloads ="
    line: "ParallelDownloads = 10"

- name: Run the equivalent of "pacman -Syu"
  become: true
  pacman:
    update_cache: true
    upgrade: true

- name: Install packages
  become: true
  pacman:
    name: "{{ pacman_packages }}"
    state: present
