---
- name: Enable pacman parallel downloading
  become: true
  lineinfile:
    path: /etc/pacman.conf
    regexp: "ParallelDownloads ="
    line: "ParallelDownloads = 10"

- name: Install pacman packages
  become: true
  pacman:
    name: "{{ pacman_packages }}"
    state: present
  notify: "pacman packages installed"
  register: result
  until: "result is not failed"
  delay: 5
  retries: 3

- name: Create pacman hooks folder
  become: true
  file:
    path: /etc/pacman.d/hooks/
    state: directory

- name: Create auto link dash to /bin/sh hook
  become: true
  template:
    src: relink-dash.hook.j2
    dest: "/etc/pacman.d/hooks/relink-dash.hook"
