---
- name: Run the equivalent of "pacman -Syu"
  become: true
  pacman:
    upgrade: true
    update_cache: true
  register: update_result
  changed_when: update_result.packages | length > 0

- name: Show updated packages
  ansible.builtin.debug:
    var: update_result.packages
  when: update_result.changed

- name: Find packages to clean
  become: true
  command: pacman -Qqdt
  register: packages_to_clean
  ignore_errors: true

- name: "Clean packages: {{ packages_to_clean.stdout_lines | join(', ') }}"
  become: true
  pacman:
    name: "{{ packages_to_clean.stdout_lines }}"
    state: absent
    extra_args: --recursive
  when: packages_to_clean.stdout_lines != []
