---
- name: Asdf plugin list
  ansible.builtin.shell:
    cmd: >
      source {{ zshrc_location }} &&
      asdf plugin list
    executable: /bin/zsh
  register: asdf_plugins
  changed_when: false
  ignore_errors: true
  vars:
    zshrc_location: "~/Projects/dotfiles/zsh/.config/zsh/.zshrc"

- name: Setup asdf-vm plugins
  ansible.builtin.shell:
    cmd: >
      source {{ zshrc_location }} &&
      asdf plugin add {{ item }} &&
      asdf install {{ item }} latest &&
      asdf global {{ item }} latest
    executable: /bin/zsh
  when: "item|string not in asdf_plugins.stdout_lines"
  changed_when: true
  vars:
    zshrc_location: "~/Projects/dotfiles/zsh/.config/zsh/.zshrc"
  loop: "{{ vm_asdf_plugins }}"

- name: Install npm packages
  ansible.builtin.shell:
    cmd: >
      source {{ zshrc_location }} &&
      npm install -g {{ item }}
    executable: /bin/zsh
  loop: "{{ npm_packages }}"
  register: npm_install_result
  changed_when: '"changed" in npm_install_result.stdout'
  vars:
    zshrc_location: "~/Projects/dotfiles/zsh/.config/zsh/.zshrc"
