---
- name: Get auto-cpufreq from GitHub
  ansible.builtin.git:
    repo: "https://github.com/AdnanHodzic/auto-cpufreq.git"
    dest: "~/Programs/auto-cpufreq"
    version: master
    update: true
    force: true
    clone: true

- name: Build auto-cpufreq
  ansible.builtin.command:
  become: true
  args:
    cmd: ./auto-cpufreq-installer --install
    chdir: "/home/{{ ansible_user }}/Programs/auto-cpufreq"
  changed_when: true

- name: Setup auto-cpufreq
  ansible.builtin.command: auto-cpufreq --install
  become: true
  changed_when: true
  ignore_errors: true
