---
- name: Get dotfiles from GitHub
  git:
    repo: "https://github.com/zahidkizmaz/dotfiles"
    dest: "~/Projects/dotfiles/"
    force: true
    clone: true

- name: Create .config folder
  file:
    path: ~/.config/
    state: directory

- name: Create autorandr config folder
  file:
    path: ~/.config/autorandr/
    state: directory

- name: Create symlinks to config files
  command: stow --adopt -RSt ~ {{ item }}
  args:
    chdir: ~/Projects/dotfiles/
  loop: "{{ config_packages }}"
