---
- name: Set the UNIX domain socket ownership to libvirt
  become: true
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: "unix_sock_group"
    line: unix_sock_group = 'libvirt'

- name: Set the UNIX socket permission to read and write.
  become: true
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: "unix_sock_rw_perms"
    line: unix_sock_rw_perms = '0770'

- name: Set the UNIX socket permission to read and write.
  become: true
  ansible.builtin.lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: 'user = "libvirt-qemu"'
    line: 'user = "{{ ansible_user }}"'
