---
- name: Creata system rules
  ansible.builtin.include_tasks:
    file: rules.yml
    apply:
      tags: rules

- name: Setup libvirt and qemu
  ansible.builtin.include_tasks:
    file: libvirt.yml
    apply:
      tags: libvirt

- name: Copy reflector config
  ansible.builtin.include_tasks:
    file: reflector.yml
    apply:
      tags: reflector

- name: Create dotfiles
  ansible.builtin.include_tasks:
    file: dotfiles.yml
    apply:
      tags: dotfiles

- name: Setup ZSH
  ansible.builtin.include_tasks:
    file: zsh.yml
    apply:
      tags: zsh

- name: Install pipx packages
  ansible.builtin.include_tasks:
    file: pipx.yml
    apply:
      tags: pipx

- name: Setup tmux
  ansible.builtin.include_tasks:
    file: tmux.yml
    apply:
      tags: tmux

- name: Install asdf-vm managed runtimes and packages
  ansible.builtin.include_tasks:
    file: asdf-vm.yml
    apply:
      tags: asdf-vm

- name: Install auto-cpufreq
  ansible.builtin.include_tasks:
    file: auto-cpufreq.yml
    apply:
      tags: auto-cpufreq

- name: Setup neovim
  ansible.builtin.include_tasks:
    file: neovim.yml
    apply:
      tags: neovim
