---
- name: Install nvim packages
  shell:
    cmd: >
      source {{ zshrc_location }} &&
      nvim --headless "+Lazy! sync" +qa
    executable: /bin/zsh
  vars:
    zshrc_location: "~/Projects/dotfiles/zsh/.config/zsh/.zshrc"
