---
- name: Clean pipx packages
  ansible.builtin.command: pipx uninstall-all
  changed_when: true

- name: Install pipx packages
  ansible.builtin.command: pipx install {{ item }}
  loop: "{{ pipx_packages }}"
  changed_when: true

- name: Inject neovim and pylsp-mypy package to python-lsp-server env
  ansible.builtin.command: pipx inject python-lsp-server neovim pylsp-mypy
  changed_when: true
