---
- name: Get installed pipx packages
  ansible.builtin.command: pipx list
  register: installed_pipx_packages
  changed_when: false

- name: Install pipx packages
  ansible.builtin.command: pipx install {{ item }}
  when: "item|string not in installed_pipx_packages.stdout"
  loop: "{{ config_pipx_packages }}"
  changed_when: true

- name: Inject neovim and pylsp-mypy package to python-lsp-server env
  ansible.builtin.command: pipx inject python-lsp-server neovim pylsp-mypy
  changed_when: true
