---
- name: Get installed pipx packages
  ansible.builtin.shell:
    cmd: >
     source {{ zshrc_location }} &&
     pipx list
    executable: /bin/zsh
  register: installed_pipx_packages
  changed_when: false
  vars:
    zshrc_location: "~/Projects/dotfiles/zsh/.config/zsh/.zshrc"

- name: Install pipx packages
  ansible.builtin.shell:
    cmd: >
     source {{ zshrc_location }} &&
     pipx install {{ item }}
    executable: /bin/zsh
  when: "item|string not in installed_pipx_packages.stdout"
  loop: "{{ config_pipx_packages }}"
  changed_when: true
  vars:
    zshrc_location: "~/Projects/dotfiles/zsh/.config/zsh/.zshrc"

- name: Inject neovim and pylsp-mypy package to python-lsp-server env
  ansible.builtin.shell:
    cmd: >
     source {{ zshrc_location }} &&
     pipx inject python-lsp-server neovim pylsp-mypy
    executable: /bin/zsh
  changed_when: true
  vars:
    zshrc_location: "~/Projects/dotfiles/zsh/.config/zsh/.zshrc"
