---
- name: Install rtx plugins
  ansible.builtin.shell:
    cmd: >
      rtx activate &&
      rtx install {{ item }}
    executable: /bin/zsh
  changed_when: true
  loop: "{{ config_rtx_plugins }}"

- name: Install npm packages
  ansible.builtin.shell:
    cmd: >
      rtx exec node@lts -- npm install -g {{ item }}
  loop: "{{ config_npm_packages }}"
  register: npm_install_result
  changed_when: '"changed" in npm_install_result.stdout'
