---
- name: Get backlight card name
  ansible.builtin.find:
    paths: /sys/class/backlight/
    recurse: false
    file_type: link
  register: backlight_result

- name: Create backlight rule
  become: true
  ansible.builtin.template:
    src: backlight.rules.j2
    dest: "/etc/udev/rules.d/backlight.rules"
    mode: "u=rw,g=r,o=r"
  vars:
    backlight: "{{ backlight_result.files.0.path | basename }}"
  when: backlight_result.files != []
