---
- name: Create backlight rule
  become: true
  copy:
    dest: "/etc/udev/rules.d/backlight.rules"
    content: |
      RUN+="/bin/chgrp video /sys/class/backlight/intel_backlight/brightness"
      RUN+="/bin/chmod g+w /sys/class/backlight/intel_backlight/brightness"
