---
- name: Get backlight card name
  find:
    paths: /sys/class/backlight/
    recurse: false
    file_type: link
  register: backlight_result

- name: Create backlight rule
  become: true
  template:
    src: backlight.rules.j2
    dest: "/etc/udev/rules.d/backlight.rules"
  vars:
    backlight: "{{ backlight_result.files.0.path | basename }}"
  when: backlight_result.files != []

- name: Create touchpad settings
  become: true
  template:
    src: 30-touchpad.conf.j2
    dest: "/etc/X11/xorg.conf.d/30-touchpad.conf"
