---
- name: Update zsh plugins
  ansible.builtin.shell:
    cmd: >
     source {{ zshrc_location }} &&
     zeesh-update
    executable: /bin/zsh
  register: zeesh_update
  changed_when: "'Updated' in zeesh_update.stdout"
  vars:
    zshrc_location: "~/Projects/dotfiles/zsh/.config/zsh/.zshrc"

- name: Update pipx packages
  ansible.builtin.command: pipx upgrade-all
  register: upgraded_pipx_packages
  changed_when: "'Versions did not change' not in upgraded_pipx_packages.stdout"

- name: Update tldr cache
  ansible.builtin.command: tldr -u
  changed_when: true

- name: Update bat cache
  ansible.builtin.command: bat cache --build
  changed_when: true

- name: Update tmux packages
  ansible.builtin.command: ~/.tmux/plugins/tpm/bin/update_plugins all
  changed_when: true

- name: Update mise plugins
  ansible.builtin.shell:
    cmd: mise plugins update
    executable: /bin/zsh
  register: updated_mise_plugins
  changed_when: |
    updated_mise_plugins.stdout != ""

- name: Upgrade mise installations
  ansible.builtin.shell:
    cmd: mise upgrade
    executable: /bin/zsh
  register: updated_mise_installations
  changed_when: |
    "all runtimes are installed" in updated_mise_installations.stdout

- name: Clean unused mise installations
  ansible.builtin.shell:
    cmd: mise prune --yes
    executable: /bin/zsh
  register: clean_mise_installations
  changed_when: |
    "removing" in clean_mise_installations.stdout

- name: Update npm global packages
  ansible.builtin.command: npm update -g
  register: updated_npm_packages
  changed_when: |
    'added' in updated_npm_packages.stdout
    or 'removed' in updated_npm_packages.stdout
    or 'changed' in updated_npm_packages.stdout

- name: Update nvim packages and treesitter grammars
  ansible.builtin.shell:
    cmd: >
      source {{ zshrc_location }} &&
      nvim --headless
      -c 'TSUpdateSync all'
      -c 'Lazy! sync'
      +qa
    executable: /bin/zsh
  register: nvim_install_result
  changed_when: |
    "Updating" in nvim_install_result.stdout
    or "Downloading" in nvim_install_result.stdout
  vars:
    zshrc_location: "~/Projects/dotfiles/zsh/.config/zsh/.zshrc"
