---
- name: Update zsh plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: master
    update: true
    force: true
    clone: true
  loop: "{{ config_zsh_plugins }}"

- name: Update pipx packages
  ansible.builtin.command: pipx upgrade-all
  register: upgraded_pipx_packages
  changed_when: "'Versions did not change' not in upgraded_pipx_packages.stdout"

- name: Update tldr cache
  ansible.builtin.command: tldr -u
  changed_when: true

- name: Update bat cache
  ansible.builtin.command: bat cache --build
  changed_when: true

- name: Update tmux packages
  ansible.builtin.command: ~/.tmux/plugins/tpm/bin/update_plugins all
  changed_when: true

- name: Update rtx plugins
  ansible.builtin.shell:
    cmd: rtx plugins update
    executable: /bin/zsh
  register: updated_rtx_plugins
  changed_when: |
    updated_rtx_plugins.stdout != ""

- name: Update rtx installations
  ansible.builtin.shell:
    cmd: rtx plugins update
    executable: /bin/zsh
  register: updated_rtx_installations
  changed_when: |
    "all runtimes are installed" in updated_rtx_installations.stdout

- name: Update npm global packages
  ansible.builtin.command: npm update -g
  register: updated_npm_packages
  changed_when: |
    'added' in updated_npm_packages.stdout
    or 'removed' in updated_npm_packages.stdout
    or 'changed' in updated_npm_packages.stdout

- name: Update nvim packages and treesitter grammars
  ansible.builtin.shell:
    cmd: >
      source {{ zshrc_location }} &&
      nvim --headless
      -c 'TSUpdateSync all'
      -c 'Lazy! sync'
      +qa
    executable: /bin/zsh
  register: nvim_install_result
  changed_when: |
    "Updating" in nvim_install_result.stdout
    or "Downloading" in nvim_install_result.stdout
  vars:
    zshrc_location: "~/Projects/dotfiles/zsh/.config/zsh/.zshrc"
