---
- name: Set zsh as default user shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
  listen: "pacman packages installed"

- name: Add user to {{ user_groups }}
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ user_groups }}"
    append: true
  listen: "pacman packages installed"
