---
- name: Set zsh as default shell for {{ ansible_user }}
  become: true
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
  listen: "pacman packages installed"

- name: Add {{ ansible_user }} to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  listen: "pacman packages installed"

- name: Add {{ ansible_user }} to libvirt group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: libvirt
    append: true
  listen: "pacman packages installed"
