---
- name: Set zsh as default shell for {{ ansible_user }}
  become: true
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
  listen: "pacman packages installed"

- name: Add {{ ansible_user }} to {{ item }} group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: "{{ item }}"
    append: true
  loop: "{{ user_groups }}"
  listen: "pacman packages installed"
