---
- name: Enable libvirtd.service
  become: true
  ansible.builtin.service:
    name: "libvirtd.service"
    enabled: true
  listen: "pacman packages installed"

- name: Enable fstrim.timer
  become: true
  ansible.builtin.service:
    name: "fstrim.timer"
    enabled: true
  listen: "pacman packages installed"

- name: Enable reflector.timer
  become: true
  ansible.builtin.service:
    name: "reflector.timer"
    enabled: true
  listen: "pacman packages installed"

- name: Build bat cache
  ansible.builtin.command: bat cache --build
  listen: "reboot done"
  changed_when: true
